### PR TITLE
Friendships v1

### PR DESCRIPTION
**Pull request by Alaska01**
Created Model and Associations for the social media project.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! You have implemented the required associations for this milestone as required. :+1: However, there are several requirements that are missing from your project. I have listed them below so that you can easily check them off as you implement them.
- [ ] As a user I should be able to send a friendship invitation. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] As a user I should be able to see friendship requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] As a user I should be able to accept friendship requests to start a friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] As a user I should be able to reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There should be a button to invite a `user` to a friendship on the users' list page and on the single user's page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] The Posts timeline should include posts written by the logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Write tests for your code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Make sure that your linter checks are running on your pull request.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Alaska01** [comment]
Fixed required changes as requested by TSE. As regards the Linters, there are no errors, and that can be confirmed locally. After careful consultation, we were told since it was a FORKED repo, and we were not the originator of the repo such issues are normally allowed and the Linter will not display on the pull request. Feel free to guide us on how to do that if there is a way of handling it that we are not aware of. We would be happy to learn about it. Thanks.

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
Great job so far @team :clap: :clap: :clap: :clap: :clap:, you are almost there :+1:, you still need to work :hammer: :toolbox: :wrench: on some minor changes to get your project approved :checkered_flag:.

Please check the comments below :point_down: :point_down: :point_down: :point_down: :point_down:.

## Required Changes:

- [ ] Add more tests to your project, write integration tests also.

- [ ] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

## Optional Requirements:

- [ ] as a user I should be able to unfriend a friend.

- [ ] as a User I should be able to cancel an invitation.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_Feel free to contact me on slack if you have any question._

**Comment by GraceOyiza** [comment]
- All required changes fixed

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 

A great effort in implementing the required changes! 👏 
Just some small changes to get the project approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck! 😺 
## Mandatory changes
- Kindly remove all your commented out code if you are not using it, ie. posts controller
- Add integration test for sign up and all the features the project provided. All your code and features must be tested.

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED ♻️ 🛑 
HELLO, @Alaska01 GOOD PROGRESS 👍🏿 I LOVE THAT YOU HAVE IMPLEMENTED ALL THE FRIENDSHIP FEATURES. HOWEVER, THERE ARE SOME CHANGES THAT NEED TO BE MADE. KINDLY CHECK BELOW ⬇️ 

- [ ]  Posts timeline includes posts written by logged-in user and their friends. At the moment there is no way for a user to create a post. I can see you have the code created by I wasn't able to create a post. 
### hint: what you should do is have a form on your homepage with a way to create a post. Or have a link to create a new post view.

bin_dir_exist

### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING 💻

**Comment by Alaska01** [comment]
Thanks for the review, we had a poor naming convention that might have made it look like we were not having a "CREATE POST" button. We had the "SAVE" button but we renamed it. Everything seems to be working fine as illustrated in this video link https://www.loom.com/share/ef46a0f60a8c4eecb6ede71cfd8d7961

**Comment by Dandush03** [comment]
# Status :rocket: Approved :rocket: 
### Great Work Guys!
# Happy Coding :+1:

**Pull request merged**
