### PR TITLE
ror-social-scaffold

### PR DESCRIPTION
**Pull request by Alaska01**
We created the ERD for the ror-social-scaffold project where the relationships were defined with Users, Posts, Comments, among others.

### CODE REVIEW

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 🔍 

HI @Alaska01 and @GraceOyiza 👋 

Just one change to make but Awesome job so far! IT's nearly perfect! 🙂 

For you friendship relationship with user remember there will be two relationships not one. One where `confirmed == true and user_id == current_user or friend_id == current_user`.
YOu simply need to add another relationship to represent this. 🙂 

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on LinkedIn or simply connect with me, would love to meet you! [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by GraceOyiza** [comment]
- All errors fixed as required by TSE

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Hi team! Well done implementing the suggested changes from the last review. :+1: I have a few optional issues for you to consider though:
- [ ] __[Optional]__ Please remove the old ERD image so that you only have the latest ERD file with the correct adjustments in your docs folder.
- [ ] __[Optional]__ Make sure you correctly configure linting so that on your next PR, the linter checks are running.
- [ ] __[Optional]__ The relationship between the `friendship` table and the `users` table, your first linking arrow indicates a many-to-many r/ship rather than a one-to-many r/ship.

_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Alaska01** [comment]
Merging to development because project was approved

**Pull request merged**
